name: Install Composer for PHP
author: David G. Moore, Jr., <david@dgmjr.io>
description: Installs composer

branding:
  icon: music
  color: blue

name: Install Composer for PHP
description: 'A composite action to install Composer'
author: David G. Moore, Jr., <david@dgmjr.io>
inputs:
  version:
    description: 'The version of Composer to install. By default, it installs the latest stable version.'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Install Composer
      run: ./.github/actions/install-composer/install-composer.sh
      shell: bash
      with:
        version: ${{ inputs.version }}
