name: Install Composer for PHP
author: David G. Moore, Jr., <david@dgmjr.io>
description: Installs composer

branding:
  icon: music
  color: blue

runs:
  using: composite
  steps:
    - name: Install Composer
      id: install-composer
      run: |
          mkdir -p /tmp
          cd ~
          curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          HASH=`curl -sS https://composer.github.io/installer.sig`
          sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
